#!/usr/bin/env sh

## DESCRIPTION
## This file lets you manage your hidden services to all its capability
##
## SYNTAX
## ./onionservice-cli command [REQUIRED] <OPTIONAL>
##
## Lines that begin with "## " try to explain what's going on. Lines
## that begin with just "#" are disabled commands.


## display error message with instructions to use the script correctly.
error_msg(){ [ -n "${1}" ] && printf %s"\033[0;31mERROR: ${1}\033[0m\n"; exit 1; }

###################
#### VARIABLES ####

## ${VAR:?STRING} -> Display an error if empty or unset.

: "${ONIONSERVICE_PWD:?$(error_msg "Export \${ONIONSERVICE_PWD} by running:\n\t./install/setup.sh -h")}"
. "${ONIONSERVICE_PWD}"/.onionrc

: "${tor_user:?}"
: "${tor_service:?}"
: "${website_dir:?}"

: "${nocolor:?}"
: "${red:?}"
: "${green:?}"
: "${yellow:?}"
: "${blue:?}"
: "${magenta:?}"

: "${data_dir:?}"
: "${data_dir_services:?}"
: "${data_dir_auth:?}"
: "${torrc_root:?}"
: "${torrc:?}"
: "${control_port:=9051}"

: "${vanguards_commit:?}"
: "${scp_target_full:?}"
: "${local_ip:?}"

while true; do
  case "${1}" in
    on|off|list|renew|web|location|backup|restore|vanguards) command="${1}"; shift;;

    auth-server|auth-client) command="${1%-*}"; host="${1#*-}"; : "${host:?$(error_msg "host is missing")}"; shift;;

    --install|--logs|--upgrade|--remove|--nginx|--apache|--html|--create|--integrate|--no-qr) action="${1#--}"; shift;;

    --on|--off|--list) status="${1#--}"; shift;;

    -s|--service) service="${2:?$(error_msg "service is missing")}"; shift 2;;
    --service=*) service="${1#*=}"; : "${service:?$(error_msg "service is missing")}"; shift;;

    -c|--client) client="${2:?$(error_msg "client is missing")}"; shift 2;;
    --client=*) client="${1#*=}"; : "${client:?$(error_msg "client is missing")}"; shift;;

    -o|--onion) onion="${2:?$(error_msg "onion is missing")}"; shift 2;;
    --onion=*) onion="${1#*-}"; : "${onion:?$(error_msg "onion is missing")}"; shift;;

    --purge) purge="${1#--}"; shift;;

    -v|--version) version="${2:-3}"; shift 2;;
    --version=*) version="${1#*=}"; : "${version:=3}"; shift;;

    -S|--socket) socket="${2:?$(error_msg "socket is missing")}"; shift 2;;
    --socket=*) socket="${1#*=}"; : "${socket:?$(error_msg "socket is missing")}"; shift;;

    --port) port="${2:?$(error_msg "port is missing")}"; shift 2;;
    --port=*) port="${1#*=}"; : "${port:?$(error_msg "port is missing")}"; shift;;

    -F|--folder) folder="${2:?$(error_msg "folder is missing")}"; shift 2;;
    --folder=*) folder="${1#*=}"; : "${folder:?$(error_msg "folder is missing")}"; shift;;

    --client-priv-key) client_priv_key="${2:?$(error_msg "client_priv_key is missing")}"; shift 2;;
    --client-priv-key=*) client_priv_key="${1#*=}"; : "${client_priv_key:?$(error_msg "client_priv_key is missing")}"; shift;;

    --client-pub-key) client_pub_key="${2:?$(error_msg "client_pub_key is missing")}"; shift 2;;
    --client-pub-key=*) client_pub_key="${1#*=}"; : "${client_pub_key:?$(error_msg "client_pub_key is missing")}"; shift;;

    --) shift; break;;
    *) break;;
  esac
done


###################
#### FUNCTIONS ####

usage(){
  onion_ascii="${ONIONSERVICE_PWD}/images/onion-ascii-closed.txt"
  if [ -f "${onion_ascii}" ]; then
    onion_ascii="$(while IFS= read -r line || [ -n "$line" ]; do printf '%s\n' "$line"; done < "${onion_ascii}")"
    printf %s"${magenta} ${onion_ascii} ${nocolor}\n\n"
  fi

  printf "Configure an Onion Service
\nUsage: %s${0##*/} command [required <args>] <optional>
\nOptions:
  on [--service <SERVICE>] [--socket <tcp|unix>] [--port=VIRTPORT[,TARGET],VIRTPORT2[,TARGET2]>] <--version 3>
                                                             enable a service (only TCP requires a target)
  off [--service <@all|SERV1,SERV2,...>] <--purge>           disable a service and optionally purge its directory
  list [--service <@all|SERV1,SERV2,...>] <--no-qr>          see credentials from indicated services
  renew [--service <@all|SERV1,SERV2,...>]                   renew indicated services addresses
  auth-server --on [--service <SERVICE>] [--client <client>] --client-pub-key <CLIENT_PUB_KEY>
                                                             add client authorization, optionally add client's public key
  auth-server --on [--service <@all|SERV1,SERV2,...>] [--client <CLIENT1,CLIENT2,...>]
                                                             add client authorization
  auth-server --off [--service <@all|SERV1,SERV2,...>] [--client <@all|CLIENT1,CLIENT2,...>]
                                                             remove client authorization
  auth-server --list [--service <@all|SERV1,SERV2,...>]      list authorized clients for indicated service
  auth-client --on [--onion <ONION>] --client-priv-key <CLIENT_PRIV_KEY>
                                                             add authorization of client access, optionally add client's private key
  auth-client --off [--onion <ONION>]                        remove authorization of client access
  auth-client --list                                         list your keys as a client
  web --on [--service <SERVICE>] [--folder <SITE_PATH>]      start serving a website for certain service and its folder
  web --off [--service <SERVICE>]                            stop serving a website for certain service and its folder
  web --list                                                 list enabled websites
  location [--nginx|--apache|--html] [--service <SERVICE>]   onion-location guide, no execution
  backup [--create|--integrate]                              restore latest torrc backup
  vanguards [--install|--logs|--upgrade|--remove]            install, upgrade, remove or see logs for vanguards addon
  [-h|--help]                                                display this help message

Description:
  @all                   all services or clients available
  SERV1,SERV2...         only specified services
  CLIENT1,CLIENT2,...    only specified services

'# Done': You should always see it at the end, else something unexpected occured.
It does not imply the code worked, you should always pay attention for errors in the logs.
If your services are unreacheable, restart tor.
\nReport bugs to: https://github.com/nyxnor/onionservice/issues\n"

  exit 1
}


## check if variable is integer
is_integer(){ printf %d "${1}" >/dev/null 2>&1 || error_msg "Not an integer: ${1}" ; }


## checks if the target is valid.
## Address range from 0.0.0.0 to 255.255.255.255. Port ranges from 0 to 65535
## this is not perfect but it is better than nothing
is_addr_port(){
  addr_port="${1}"
  port="${addr_port##*:}"
  addr="${addr_port%%:*}"
  addr_1="${addr%%.*}"
  addr_mid="${addr##*"${addr_1}".}"
  addr_2="${addr_mid%%.*}"
  addr_4="${addr_mid##*.}"
  addr_mid="${addr_mid##*"${addr_2}".}"
  addr_3="${addr_mid%%.*}"

  is_integer "${port}"; is_integer "${addr_1}"; is_integer "${addr_2}"; is_integer "${addr_3}"; is_integer "${addr_4}"

  { [ "${port}" -gt 0 ] && [ "${port}" -le 65535 ] ; } \
  || error_msg "port is not within range: 0 < port <= 65535: ${port}"

  { { [ "${addr_1}" -ge 0 ] && [ "${addr_1}" -le 255 ] ; } \
  && { [ "${addr_2}" -ge 0 ] && [ "${addr_2}" -le 255 ] ; } \
  && { [ "${addr_3}" -ge 0 ] && [ "${addr_3}" -le 255 ] ; } \
  && { [ "${addr_4}" -ge 0 ] && [ "${addr_4}" -le 255 ] ; } ; } \
  || error_msg "target address is not within range: 0.0.0.0 to 255.255.255.255: ${addr}"
}


is_service_dir_empty(){
  [ "$(sudo -u "${tor_user}" ls "${data_dir_services}"/)" = "" ] && error_msg "Onion services directory is empty. Create a service first before running this command again."
}


## test if service exists to continue the script or output error logs.
## if the service exists, will save the hostname for when requested.
test_service_exists(){
  service="${1}"
  onion_hostname=$(sudo -u "${tor_user}" grep -s ".onion" "${data_dir_services}"/"${service}"/hostname)
  [ -z "${onion_hostname}" ] && { printf %s"${red}ERROR: Service does not exist: ${service}\n${nocolor}"; exit 1; }
}


## save the clients names that are inside the <HiddenServiceDir>/authorized_clients/ in list format (CLIENT1,CLIENT2,...)
create_client_list(){
  service="${1}"
  client_name_list="$(printf %s"$(sudo -u "${tor_user}" ls "${data_dir_services}"/"${service}"/authorized_clients/)" | sed "s/\.auth//g" | tr "\n" ",")"
  client_count=""
  # shellcheck disable=SC2086
  [ -n "${client_name_list}" ] && client_count="$(IFS=','; set -f -- ${client_name_list}; printf %s"${#}")"
}


## save the service names that have a <HiddenServiceDir> in list format (SERV1,SERV2,...)
create_service_list(){ service_name_list=$(sudo -u "${tor_user}" ls "${data_dir_services}"/ | tr " " ","); }


## loops the parameters
## $1 must be the function to loop
## $2 normally is service, but can be any other parameter (accepts list -> SERV1,SERV2,...)
## $3 normally is client, but can be any other (accepts list -> client1,client2...)
loop_list(){
  for item in $(printf %s"${2}" | tr "," " "); do
    if [ -z "${3}" ]; then
      "${1}" "${item}"
    else
      for subitem in $(printf %s"${3}" | tr "," " "); do
        "${1}" "${item}" "${subitem}"
      done
    fi
  done
}


###########################
########## MAIN ###########
sudo sed -i'' 's/\/$//' "${torrc}" ## no config should end with '/' to find exact match.
service="$(printf %s"${service}" | tr "," " " | tr -s " ")"

case "${command}" in

  ## disabled the service wrongly and don't remember the ports? no worries, will restore the latest torrc.bak
  ## beaware this only works for the torrc, if you deleted your data directory with command "off" and "purge" option, the keys will not be restored, insteadm new ones will be created
  restore|RESTORE)
    : "${action:?$(usage)}"
    case "${action}" in

      torrc|TORRC)
        ## separate HiddenService liens to the end of the torrc
        printf '\n%s\n\n' "$(sudo sed -n "/HiddenServiceDir/,/^\s*$/{p}" "${torrc}".bak)" | sudo tee "${torrc}".tmp >/dev/null
        sudo sed "/HiddenServiceDir/,/^\s*$/{d}" "${torrc}" | sudo tee "${torrc}".mod >/dev/null
        sudo cat -s "${torrc}".mod "${torrc}".tmp | sudo tee "${torrc}" >/dev/null
        printf "# Restored torrc with its latest backup\n"
        restarting_tor
        printf %s"${green}\n# Done\n${nocolor}"
      ;;

      *)
        error_msg "Invalid argument: ${action}"
      ;;
    esac
  ;;


  ## disable a service by removing service torrc's block.
  ## it is raw, services variables should be separated by an empty line per service, else you might get other non-related configuration deleted.
  ## purge is optional, it deletes the <HiddenServiceDir>
  ## will not check if folder or configuration exist, this is cleanup mode
  ## will not use '@all'. Purge is dangerous, purging all service is even more dangerous. Always backup.
  off|OFF)
    : "${service:?$(error_msg "service is missing")}"
    : "${purge}" ## optional
    delete_service(){
      service="${1}"
      purge="${2}"
      ## remove service service data
      if [ "${purge}" = "PURGE" ] || [ "${purge}" = "purge" ]; then
        printf %s"${red}\n# Deleted Hidden Service data in ${data_dir_services}/${service}\n${nocolor}"
        sudo rm -rfv "${data_dir_services}"/"${service}"
      else
        printf "\n# HiddenServiceDiretory was kept\n"
      fi
      sudo cp "${torrc}" "${torrc}".bak
      ## remove service paragraph in torrc
      printf %s"# Deleted Hidden Service configuration in ${torrc}\n"
      sudo sed -i'' "/HiddenServiceDir .*\/${service}$/,/^\s*$/{d}" "${torrc}"
      ## substitute multiple sequential empty lines to a single one per sequence
      sudo cat -s "${torrc}" | sudo tee "${torrc}".tmp >/dev/null && sudo mv "${torrc}".tmp "${torrc}"
      printf %s"# Disabled service: ${service}\n\n"
    }
    loop_list delete_service "${service}" "${purge}"
    restarting_tor
    printf %s"${green}\n# Done\n${nocolor}"
  ;;


  ## enable a service by configure its own torrc's block, consequentially the <HiddenServiceDir> will be created.
  ## tcp-socket uses addr:port, which can be remote or localhost. It leaks onion address to the local network
  ## unix-socket uses unix:path, which is create a unique name for it. It does not leak onion address to the local network.
  ## virtport is the port to be used by the client when visiting the service.
  ## target is where the incoming traffic from virtport gets redirected. This option is abscent on unix-socket because the script completes it.
  ##  if target is not specified, will use the same port from virtport and bind to localhost.
  ##  if target only contains the port number and not the address, will bind to localhost.
  ## virtport2 and target 2 are optional
  on|ON)
    : "${service:?$(error_msg "service is missing")}"
    : "${socket:?$(error_msg "socket is missing")}"
    : "${version:=3}"; [ "${version}" != "3" ] && error_msg "version=${version} is not available" ## wait for v4 to change this
    : "${port:?$(error_msg "port is missing")}"
    port="$(printf %s"${port}" | tr "," " " | tr -s " ")"
    virtport="${port%% *}"
    : "${virtport:?$(error_msg "virtport is missing")}"

    finish_service_activation(){
      ## remove double empty lines
      sudo cat -s "${torrc}" | sudo tee "${torrc}".tmp >/dev/null && sudo mv "${torrc}".tmp "${torrc}"
      restarting_tor
      ## show the Hidden Service address
      test_service_exists "${service}"
      printf "\n# Hidden Service information:\n"
      qrencode -m 2 -t ANSIUTF8 "${onion_hostname}"
      printf %s"Service name    = ${service}\n"
      printf %s"Service address = ${onion_hostname}\n"
      printf %s"Virtual port    = ${virtport}\n"
      [ -n "${virtport2}" ] && printf %s"Virtual port 2  = ${virtport2}\n"
      printf %s"${green}\n# Done\n${nocolor}"
    }

    case "${socket}" in

      tcp|TCP)
        ## tor-manual: By default, this option maps the virtual port to the same port on 127.0.0.1 over TCP
        ## Because of that, this project lets the user leave target="" and write target as 127.0.0.1:$virtport
        ## Also, substitutes localhost:port for 127.0.0.1:$port
        ## This measures avoid using the same local port for different services
        ## grep torrc target to see if port is already in use and by which service, reading the file in reverse
        ## Sanity check
        port_mid="${port##*"${virtport}" }"
        target="${port_mid%% *}"
        port_mid="${port_mid##*"${target}" }"
        virtport2="${port_mid%% *}"
        target2="${port##* }"
        { [ "${virtport}" = "${virtport2}" ] || [ "${target}" = "${virtport2}" ]; } && virtport2=""
        [ "${target}" = "${target2}" ] && error_msg "target is the same as target2 -> ${target}=${target2}"
        : "${target:=127.0.0.1:"${virtport}"}"
        : "${target2:=127.0.0.1:"${virtport2}"}"
        ## Standard check for used ports
        target_addr="${target%%:*}"
        target_port="${target##*:}"
        { [ "${target_addr}" = "${target_port}" ] || [ "${target_addr}" = "localhost" ]; } && target="127.0.0.1:${target_port}"
        target_already_inserted_block="$(sudo tac "${torrc}" | sudo sed -n "/^HiddenServicePort .*${target}$/,/^\s*$/{p}" | grep "^HiddenServiceDir")"
        target_already_inserted_service="${target_already_inserted_block##*/}"
        sudo grep -q "^HiddenServicePort .* ${target}$" "${torrc}" && error_msg "target=${target} is being used by the service: ${target_already_inserted_service}\nINFO: Choose another port or disable the service that is using the wanted port."
        is_integer "${virtport}"; is_addr_port "${target}"
        ## Optional
        if [ -n "${virtport2}" ]; then
          ## Standard check for used ports
          target2_addr="${target2%%:*}"
          target2_port="${target2##*:}"
          { [ "${target2_addr}" = "${target2_port}" ] || [ "${target2_addr}" = "localhost" ]; } && target2="127.0.0.1:${target2_port}"
          target2_already_inserted_block="$(sudo tac "${torrc}" | sudo sed -n "/^HiddenServicePort .*${target2}$/,/^\s*$/{p}" | grep "^HiddenServiceDir")"
          target2_already_inserted_service="${target2_already_inserted_block##*/}"
          sudo grep -q "^HiddenServicePort .* ${target2}$" "${torrc}" && error_msg "target2=${target2} is being used by the service: ${target2_already_inserted_service}\nINFO: Choose another port or disable the service that is using the wanted port."
          is_integer "${virtport2}"; is_addr_port "${target2}"
        fi
        sudo cp "${torrc}" "${torrc}".bak
        ## delete any old entry for that servive
        sudo sed -i'' "/HiddenServiceDir .*\/${service}$/,/^\s*$/{d}" "${torrc}"
        ## add configuration block, empty line after and before it
        printf %s"\n# Including Hidden Service configuration in ${torrc}\n"
        if [ -n "${virtport2}" ]; then
          printf %s"\nHiddenServiceDir ${data_dir_services}/${service}\nHiddenServiceVersion ${version}\nHiddenServicePort ${virtport} ${target}\nHiddenServicePort ${virtport2} ${target2}\n\n" | sudo tee -a "${torrc}"
        else
          [ -n "${virtport2}" ] || printf %s"\nHiddenServiceDir ${data_dir_services}/${service}\nHiddenServiceVersion ${version}\nHiddenServicePort ${virtport} ${target}\n\n" | sudo tee -a "${torrc}"
        fi
        finish_service_activation
      ;;

      unix|UNIX)
        is_integer "${virtport}"
        virtport2="${port##* }"
        [ "${virtport}" = "${virtport2}" ] && virtport2=""
        [ -n "${virtport2}" ] && is_integer "${virtport2}" ## var not mandatory
        sudo cp "${torrc}" "${torrc}".bak
        ## delete any old entry for that servive
        sudo sed -i'' "/HiddenServiceDir .*\/${service}$/,/^\s*$/{d}" "${torrc}"
        ## add configuration block, empty line after and before it
        printf %s"\n# Including Hidden Service configuration in ${torrc}\n"
        unix_path="unix:/var/run/${service}-onion"
        if [ -n "${virtport2}" ]; then
          printf %s"\nHiddenServiceDir ${data_dir_services}/${service}\nHiddenServiceVersion ${version}\nHiddenServicePort ${virtport} ${unix_path}-${virtport}.sock\nHiddenServicePort ${virtport2} ${unix_path}-${virtport2}.sock\n\n" | sudo tee -a "${torrc}"
        else
          [ -n "${virtport2}" ] || printf %s"\nHiddenServiceDir ${data_dir_services}/${service}\nHiddenServiceVersion ${version}\nHiddenServicePort ${virtport} ${unix_path}-${virtport}.sock\n\n" | sudo tee -a "${torrc}"
        fi
        finish_service_activation
      ;;

      *)
        error_msg "Invalid argument: socket=${socket}"
    esac
  ;;


  ## manage client authorization server side (HiddenServiceDir/authorized_clients/) or client side (ClientOnionAuthDir)
  auth|AUTH)
    : "${host:?$(error_msg "host is missing")}"
    : "${status:?$(error_msg "status is missing")}"
    case "${host}" in

      server|SERVER)
        is_service_dir_empty
        : "${service:?$(error_msg "service is missing")}"
        case "${status}" in

          ## as the onion service operator, make your onion authenticated by generating a pair or public and private keys,
          ## the client pub key is automatically saved inside <HiddenServiceDir>/authorized_clients/alice.auth
          ## the client private key is shown in the screen and the key file deleted
          ## the onion service operator should send the private key for the desired client
          on|ON)
            : "${client:?$(error_msg "client is missing")}"
            #printf "\n# Generating keys to access onion service (Client Authorization) ...\n"
            auth_server_add(){
              service="${1}"
              client="${2}"
              test_service_exists "${service}"
              ## Generate pem and derive pub and priv keys
              openssl genpkey -algorithm x25519 -out /tmp/k1.prv.pem
              grep -v " PRIVATE KEY" /tmp/k1.prv.pem | base64pem -d | tail --bytes=32 | base32 | sed "s/=//g" > /tmp/k1.prv.key
              openssl pkey -in /tmp/k1.prv.pem -pubout | grep -v " PUBLIC KEY" | base64pem -d | tail --bytes=32 | base32 | sed "s/=//g" > /tmp/k1.pub.key
              ## save variables
              client_pub_key=$(cat /tmp/k1.pub.key)
              client_priv_key=$(cat /tmp/k1.prv.key)
              onion_hostaname_without_onion="${onion_hostname%.onion}"
              client_priv_key_config="${onion_hostname%.onion}:descriptor:x25519:${client_priv_key}"
              client_pub_key_config="descriptor:x25519:${client_pub_key}"
              # Server side configuration
              printf %s"${client_pub_key_config}\n" | sudo tee "${data_dir_services}"/"${service}"/authorized_clients/"${client}".auth >/dev/null
              ## Client side configuration
              printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
              printf "# Declare the variables\n"
              printf %s"service=${service}\n"
              printf %s"client=${client}\n"
              printf %s"onion_hostname=${onion_hostname}\n"
              printf %s"client_pub_key=${client_pub_key}\n"
              printf %s"client_pub_key_config=${client_pub_key_config}\n"
              printf %s"client_priv_key=${client_priv_key}\n"
              printf %s"client_priv_key_config=${client_priv_key_config}\n"
              printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n\n"
              ## Delete pem and keys
              sudo rm -f /tmp/k1.pub.key /tmp/k1.prv.key /tmp/k1.prv.pem
            }
            instructions_auth(){
              printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
              printf "# Send these instructions to the client:\n"
              printf "\n"
              printf "# Check if <ClientOnionAuthDir> was configured in the <torrc>, if it was not, insert it: ClientOnionAuthDir /var/lib/tor/onion_auth\n"
              printf " [ \$(grep -c 'ClientOnionAuthDir' /etc/tor/torrc) -eq 0 ] && { printf 'ClientOnionAuthDir /var/lib/tor/onion_auth' | sudo tee -a /etc/tor/torrc ; }\n"
              printf "\n"
              printf "# Create a file with the suffix '.auth_private' inside <ClientOnionAuthDir>\n"
              printf " printf '\${client_priv_key_config}' | sudo tee /var/lib/tor/onion_auth/\${service}-\${onion_hostname}.auth_private\n"
              printf "\n"
              printf "# Reload tor\n"
              printf " sudo chown -R debian-tor:debian-tor /var/lib/tor\n"
              printf " sudo systemctl reload-or-restart tor\n"
              printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
            }
            [ "${service}" = "@all" ] && { create_service_list ; service="${service_name_list}" ; }
            [ "${client}" = "@all" ] && error_msg "Client name cannot be @all, it is a restricted wildcard for referring to all clients, not a name per se."
            if [ -n "${client_pub_key}" ]; then
              test_service_exists "${service}"
              client_pub_key_config="descriptor:x25519:${client_pub_key}"
              printf %s"${client_pub_key_config}" | sudo tee "${data_dir_services}"/"${service}"/authorized_clients/"${client}".auth >/dev/null
              printf "\n# Server side authorization configured\n\n"
              printf %s" client_pub_key_config=${client_pub_key_config}\n"
              printf "\n# As you inserted the public key manually, we expect that the client already has the private key\n"
            else
              loop_list auth_server_add "${service}" "${client}"
              instructions_auth
            fi
            restarting_tor
            printf %s"${green}\n# Done\n${nocolor}"
          ;;

          ## as the onion service operator, after making your onion service authenticated, you can also remove a specific client authorization
          ## if no clients are present, the service will be available to anyone that has the onion service address
          off|OFF)
            : "${client:?$(error_msg "client is missing")}"
            auth_server_remove_clients(){
              service="${1}"
              client="${2}"
              printf %s"Service  = ${service}\n"
              if [ "${client}" = "@all" ]; then
                printf "Client   = @all\n\n"
                sudo rm -fv "${data_dir_services}"/"${service}"/authorized_clients/*.auth
              else
                printf %s"Client   = ${client}\n\n"
                sudo rm -fv "${data_dir_services}"/"${service}"/authorized_clients/"${client}".auth
              fi
            }
            [ -z "${service}" ] && error_msg "service is missing"
            if [ "${service}" = "@all" ]; then
              printf "# Removing client authorization for all services.\n"
              create_service_list; service="${service_name_list}"
              [ "${client}" = "@all" ] \
              && printf "# Removing client authorization for all clients.\n# The service is now accessible for anyone with the onion address.\n\n" \
              || printf "# If any client remains, the service will still be authenticated.\n\n"
            else
              printf %s"# Removing client authorization for the services: ${service}\n"
              [ "${client}" = "@all" ] \
              && printf "# Removing client authorization for all clients.\n# The service is now accessible for anyone with the onion address.\n\n" \
              || printf "# If any client remains, the service will still be authenticated.\n\n"
            fi
            loop_list auth_server_remove_clients "${service}" "${client}"
            restarting_tor
            printf %s"${green}\n# Done\n${nocolor}"
          ;;

          list|LIST)
            auth_server_list(){
              service="${1}"
              test_service_exists "${service}"
              create_client_list "${service}"
              if [ -n "${client_count}" ]; then
                printf %s"\nService  = ${service}\n"
                [ -n "${client_name_list}" ] && printf %s"Clients  = ${client_name_list} (${client_count})\n"
                for AUTH in $(sudo -u "${tor_user}" ls "${data_dir_services}/${service}/authorized_clients/"); do
                  printf %s"\n# File name: ${AUTH}\n"
                  printf %s"# Content:   $(sudo -u "${tor_user}" grep "descriptor:x25519:" "${data_dir_services}"/"${service}"/authorized_clients/"${AUTH}")\n"
                done
                printf "\n"
              else
                printf %s"\n# No clients for Hidden Service: ${service}\n\n"
              fi
            }
            printf "# Authorized clients for Hidden Services\n"
            [ "${service}" = "@all" ] && { create_service_list; service="${service_name_list}"; }
            loop_list auth_server_list "${service}"
            printf %s"${green}\n# Done\n${nocolor}"
          ;;

          *)
            error_msg "Invalid argument: status=${status}"
        esac
      ;;


      client|CLIENT)
        case "${status}" in

          ## as the onion service client, add a key given by the onion service operator to authenticate yourself inside ClientOnionAuthDir
          ## The suffix '.auth_private' should not be mentioned, it will be automatically inserted when mentioning the name of the file.
          ## private key format must be: <onion-addr-without-.onion-part>:descriptor:x25519:<private-key>
          ## use the onion hostname as the file name, this avoid overriding the file by mistake and it indicates outside of the file for which service it refers to (of course it is written inside also)
          ## adding to Tor Browser automatically not supported yet
          on|ON)
            : "${onion:?$(error_msg "onion is missing")}"
            onion_hostaname_without_onion=${onion%.onion}
            suffix_onion=${onion##*.}
            [ "${onion_hostaname_without_onion%%*[^a-z2-7]*}" ] || error_msg "ONION_DOMAIN is invalid, it is not within base32 alphabet lower-case encoding [a-z][2-7]"
            [ "${#onion}" = "62" ] || error_msg "ONION_DOMAIN is invalid, LENGTH=${#onion} is different than 62 characters (<56-char-base32>.onion)"
            [ "${suffix_onion}" = "onion" ] || error_msg "ONION_DOMAIN is invalid, suffix is not '.onion'"
            sudo cp "${torrc}" "${torrc}".bak
            grep -q "ClientOnionAuthDir" "${torrc}" && { printf %s"\nClientOnionAuthDir ${data_dir_auth}\n\n" | sudo tee -a "${torrc}"; }
            sudo -u "${tor_user}" mkdir -p "${data_dir_auth}"
            if [ -z "${client_priv_key}" ]; then
              ## Generate pem and derive pub and priv keys
              openssl genpkey -algorithm x25519 -out /tmp/k1.prv.pem
              grep -v "PRIVATE KEY" /tmp/k1.prv.pem | base64pem -d | tail --bytes=32 | base32 | sed 's/=//g' > /tmp/k1.prv.key
              openssl pkey -in /tmp/k1.prv.pem -pubout | grep -v "PUBLIC KEY" | base64pem -d | tail --bytes=32 | base32 | sed 's/=//g' > /tmp/k1.pub.key
              ## save variables
              client_pub_key=$(cat /tmp/k1.pub.key)
              client_priv_key=$(cat /tmp/k1.prv.key)
              client_priv_key_config="${onion%.onion}:descriptor:x25519:${client_priv_key}"
              client_pub_key_config="descriptor:x25519:${client_pub_key}"
              ## Delete pem and keys
              sudo rm -f /tmp/k1.pub.key /tmp/k1.prv.key /tmp/k1.prv.pem
              # Client side configuration
              printf %s"${client_priv_key_config}\n" | sudo tee "${data_dir_auth}"/"${onion}".auth_private >/dev/null
              printf "# Client side authorization configured\n"
              printf "# This is your private key, keep it safe, keep it hidden:\n\n"
              printf %s" client_priv_key=${client_priv_key}\n"
              printf %s" client_priv_key_config=${client_priv_key_config}\n"
              printf "\n# Now it depends on the service operator to authorize you client public key\n\n"
              ## Server side configuration
              printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
              printf "# Send the public key and instructions to the onion service operator\n\n"
              printf %s" onion=${onion}\n"
              printf %s" client_pub_key=${client_pub_key}\n"
              printf %s" client_pub_key_config=descriptor:x25519:${client_pub_key}\n\n"
              printf "# Create a file with the client name (eg. alice) using the suffix '.auth' (eg. alice.auth) inside the folder\n"
              printf %s"#  '<HiddenServiceDir>/authorized_clients/' where the service hostname is ${onion}\n\n"
              printf %s" printf '${client_pub_key_config}' | sudo tee /var/lib/tor/hidden_service/authorized_clients/alice.auth\n\n"
              printf "# Reload tor\n\n"
              printf " sudo chown -R debian-tor:debian-tor /var/lib/tor\n"
              printf " sudo systemctl reload-or-restart tor\n"
              printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
            else
              client_priv_key_config="${onion%.onion}:descriptor:x25519:${client_priv_key}"
              printf %s"${client_priv_key_config}\n" | sudo tee "${data_dir_auth}"/"${onion}".auth_private >/dev/null
              printf "\n# Client side authorization configured\n"
              printf %s"\n client_priv_key_config=${client_priv_key_config}\n"
              printf "\n# As you inserted the private key manually, we expect that you have already sent/received the public key to/from the onion service operator\n"
            fi
            printf %s"${green}\n# Done\n${nocolor}"
          ;;

          ## as the onion service client, delete '.auth_private' files from ClientOnionAuthDir that are not valid or has no use anymore
          off|OFF)
            : "${onion:?$(error_msg "onion is missing")}"
            auth_client_remove  (){
              onion="${1}"
              printf %s"\n# Removing ${data_dir_auth}/${onion}.auth_private"
              sudo rm -fv "${data_dir_auth}"/"${onion}".auth_private
            }
            if [ "$(sudo -u "${tor_user}" ls "${data_dir_auth}")" != "" ]; then
              loop_list auth_client_remove "${onion}"
              printf "\n# Client side authorization removed\n"
              printf %s"${green}\n# Done\n${nocolor}"
            else
              printf %s"${red}INFO: ClientOnionAuthDir is empty\n${nocolor}"
            fi
          ;;

          list|LIST)
            if [ "$(sudo -u "${tor_user}" ls "${data_dir_auth}")" != "" ]; then
              printf %s"# ClientOnionAuthDir ${data_dir_auth}\n"
              for AUTH in $(sudo -u "${tor_user}" ls "${data_dir_auth}"); do
                printf %s"\n# File name: ${AUTH}\n"
                printf %s"# Content:   $(sudo -u "${tor_user}" grep "descriptor:x25519:" "${data_dir_auth}"/"${AUTH}")"
              done
              printf "\n"
              printf %s"${green}\n# Done\n${nocolor}"
            else
              printf %s"${red}INFO: ClientOnionAuthDir is empty\n${nocolor}"
            fi
          ;;

          *)
            error_msg "Invalid argument: status=${status}"
        esac
      ;;

      *)
        error_msg "Invalid argument: host=${host}"
    esac
  ;;


  ## change service hostname by deleting its ed25519 pub and priv keys.
  ## <HiddenServiceDir>/authorized_clients/ because the would need to update their '.auth_private' file with the new onion address anyway and for security reasons.
  ## @all will read through all services folders and execute the commands.
  ## TODO -> Loop services, save hostname, reload tor once and show results.
  renew|RENEW)
    is_service_dir_empty
    : "${service:?$(error_msg "service is missing")}"
    renew_service_address(){
      service="${1}"
      test_service_exists "${service}"
      printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
      printf %s"\n# Renewing hostname (address) of the service: ${service}\n"
      old_hostname="${onion_hostname}"
      ## delete service public and secret keys
      sudo rm -fv "${data_dir_services}"/"${service}"/hs_ed25519_secret_key
      sudo rm -fv "${data_dir_services}"/"${service}"/hs_ed25519_public_key
      sudo rm -fv "${data_dir_services}"/"${service}"/hostname
      ## reload tor now so auth option can get the new hostname
      restarting_tor
      test_service_exists "${service}"
      new_hostname="${onion_hostname}"
      if [ "${old_hostname}" != "${new_hostname}" ]; then
        printf %s"${blue}# Service renewed.\n${nocolor}"
        printf %s"\nOld = ${old_hostname}\n"
        printf %s"New = ${onion_hostname}\n"
        printf "\n# Note: Remember to notify your clients about the new hostname and update their '.auth_private' files accordingly.\n"
      else
        printf %s"${red}# Failed to renew service: ${service}\n${nocolor}"
      fi
      printf ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
    }
    [ "${service}" = "@all" ] && { create_service_list; service="${service_name_list}"; }
    loop_list renew_service_address "${service}"
    printf %s"${green}\n# Done\n${nocolor}"
  ;;

  ## show all the necessary information to access the service such as the hostname and the QR encoded hostname to scan for Tor Browser Mobile
  ## show the clients names and quantity, as well as the service torrc's block
  ## @all will read through all services folders and execute the commands
  list|LIST)
    is_service_dir_empty
    : "${service:?$(error_msg "service is missing")}"
    get_service_info(){
      service="${1}"
      test_service_exists "${service}"
      ## save clients names that are inside <HiddenServiceDir>/authorized_clients/
      create_client_list "${service}"
      [ "${action}" = "no-qr" ] || { printf "\n"; qrencode -m 2 -t ANSIUTF8 "${onion_hostname}"; }
      printf %s"\nAddress  = ${onion_hostname}\n"
      printf %s"Service  = ${service}\n"
      [ -n "${client_name_list}" ] && printf %s"Clients  = ${client_name_list} (${client_count})\n"
      if sudo grep -q "^HiddenServiceDir .*/${service}$" "${torrc}"; then
        printf "Status   = active\n" && sudo sed -n "/HiddenServiceDir .*\/${service}$/,/^\s*$/{p}" "${torrc}" | sed "/^[[:space:]]*$/d"
      else
        printf "Status   = inactive\n"
      fi
      printf "\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
    }
    [ "${service}" = "@all" ] && { create_service_list; service="${service_name_list}"; }
    loop_list get_service_info "${service}"
    printf %s"${green}\n# Done\n${nocolor}"
  ;;

  ## start serving files with a webserver for a specific onion service and specific website folder
  web|WEB)
    : "${web_server:?$(error_msg "web_server is missing")}"
    : "${status:?$(error_msg "status is missing")}"
    case "${status}" in

      on|ON)
        is_service_dir_empty
        : "${service:?$(error_msg "service is missing")}"
        : "${folder:?$(error_msg "folder is missing")}"
        test_service_exists "${service}"
        port=$(sudo sed -n "/HiddenServiceDir .*\/${service}$/,/^\s*$/{p}" "${torrc}" | grep "HiddenServicePort" | tail -n 1)
        only_ports=${port#* }
        virtport=${only_ports% *}
        target=${only_ports##* }
        printf %s"# Activating web server for the onion service: ${service}\n\n"
        cp -v "${ONIONSERVICE_PWD}"/etc/"${web_server}"/sites-available/sample-onion.conf /tmp/"${service}"-onion.conf
        sed -i'' "s|service|${service}|g" /tmp/"${service}"-onion.conf
        sed -i'' "s|target|${target}|g" /tmp/"${service}"-onion.conf
        ## If starts with '~/' or '/', user specified the path, if started with anything else expect a folder inside ${website_dir}
        case "${folder}" in
          ~/*|/*) sed -i'' "s|folder|${folder}|" /tmp/"${service}"-onion.conf;;
          *) sed -i'' "s|folder|${website_dir}/${folder}|" /tmp/"${service}"-onion.conf
        esac
        sudo cp -v /tmp/"${service}"-onion.conf /etc/"${web_server}"/sites-available/
        sudo ln -sfv /etc/"${web_server}"/sites-available/"${service}"-onion.conf /etc/"${web_server}"/sites-enabled/
        printf "\n# Web server configuration:\n\n"
        #sudo cat /tmp/"${service}"-onion.conf
        while IFS= read -r line || [ -n "$line" ]; do printf '%s\n' "$line"; done < "/tmp/${service}-onion.conf"
        printf "\n# Reloading web server to apply new configuration\n"
        case "${web_server}" in
          nginx) sudo nginx -t && sudo nginx -s reload;;
          apache2) sudo apache2 -t && sudo apache -k graceful;;
        esac
        #sudo rm -f /tmp/"${service}"-onion.conf
        printf %s"\n# Address: http://${onion_hostname}:${virtport}\n"
        printf %s"${green}\n# Done\n${nocolor}"
      ;;

      off|OFF)
        : "${service:?$(error_msg "service is missing")}"
        disable_site(){
          service="${1}"
          printf %s"\n# Stopping website of the service: ${service}\n"
          sudo rm -fv /etc/"${web_server}"/sites-available/"${service}"-onion.conf ## for cleanliness
          sudo rm -fv /etc/"${web_server}"/sites-enabled/"${service}"-onion.conf
        }
        loop_list disable_site "${service}" 0
        printf "\n# Reloading web server to apply new configuration\n"
        case "${web_server}" in
          nginx) sudo nginx -t && sudo nginx -s reload;;
          apache2) sudo apache2 -t && sudo apache2 -k graceful;;
        esac
        printf %s"${green}\n# Done\n${nocolor}"
      ;;

      list|LIST)
        printf %s"# Web server = ${web_server}\n\n"
        printf "# Enabled websites:"
        sites_enabled=$(sudo ls /etc/"${web_server}"/sites-enabled/ | sed "s/-onion.conf//g")
        [ -n "${sites_enabled}" ] && printf %s"\n${sites_enabled}\n" || printf " No website enabled\n"
      ;;

      *)
        error_msg "Invalid argument: ${status}"
    esac
  ;;


  ## guide to add onion-location to redirect tor users when using your plainnet site to the onion service address
  ## https://matt.traudt.xyz/posts/website-setup/
  location|LOCATION)
    is_service_dir_empty
    : "${action:?$(usage)}"
    : "${service:?$(error_msg "service is missing")}"
    test_service_exists "${service}"

    start_location(){
    printf "# Onion-Location guided steps
\n* The below output is printing text, no file was modified by this script, therefore, user needs to manually configure.
* For web servers, include header line inside the plainnet ssl block (port 443).
* It assumes you know how to run a plainnet server, configuration is an example and should be adapted to your needs.
\n# Add to your \"%s${action}\" configuration:\n"
}

  finish_location(){
  printf "\n# Test redirection
\n* Open the web site in Tor Browser and a purple pill will appear in the address bar; or
* Fetch the web site HTTP headers and look for onion-location entry and the onion service address:
\n\twget --server-response --spider your-website.tld\n"
}

    case "${action}" in

      nginx|NGINX)
        start_location
        printf "
server {\n\tlisten 443 ssl http2;\n\tadd_header Onion-Location http://""%s${onion_hostname}""\$request_uri;\n}
\n# Reload web server:\n\n\tsudo nginx -t && sudo nginx -s reload\n"
        finish_location
      ;;

      apache|APACHE)
        start_location
        printf "
<VirtualHost *:443>\n\tHeader set Onion-Location \"http://%s${onion_hostname}%%{REQUEST_URI}s\"\n</Virtualhost>
\n# Enable headers and rewrite modules:\n\n\tsudo a2enmod headers rewrite
\n# Reload web server:\n\n\tsudo apache2 -t && sudo apache2 -k graceful\n"
        finish_location
      ;;

      html|HTML)
        start_location
        printf "
<meta http-equiv=\"onion-location\" content=\"http://%s${onion_hostname}\"/>
\n# Reload web server that you use:\n\n\tsudo nginx -t && sudo nginx -s reload\n\t# or\n\tsudo apache2 -t && sudo apache2 -k graceful\n"
        finish_location
      ;;

      *)
        error_msg "Invalid argument: ${action}"
    esac
  ;;


  backup|BACKUP)
    : "${action:?$(usage)}"
    case "${action}" in

      ## restore backup
      ## backup tar file will be extracted and integrated into their respective tor folders
      ## scp instructions to import backup from remote host
      integrate|INTEGRATE)
        # shellcheck disable=SC2153,SC2154
        sudo -u "${USER}" mkdir -p "${hs_bk_dir}"/integrate
        HS_BK_TAR=$(sudo -u "${USER}" ls "${hs_bk_dir}" | grep ".tar.gz" | tail -n -1)
        printf %s"# Integrating backup from file: ${HS_BK_TAR}\n\n"
        printf "# Extracting the archive\n\n"
        sudo tar -xpzvf "${hs_bk_dir}"/"${HS_BK_TAR}" -C "${hs_bk_dir}"/integrate
        sudo chown -R "${USER}:${USER}" "${hs_bk_dir}"
        sudo cp -rf "${hs_bk_dir}"/integrate"${data_dir_services}"/* "${data_dir_services}"/
        sudo cp -rf "${hs_bk_dir}"/integrate"${data_dir_auth}"/* "${data_dir_auth}"/
        data_dir_auth_BK="$(sudo grep "ClientOnionAuthDir" "${hs_bk_dir}"/integrate"${torrc}")"
        if [ -n "${data_dir_auth_BK}" ]; then
          sudo sed -i'' "/ClientOnionAuthDir .*/d" "${torrc}"
          printf '\n%s\n\n' "${data_dir_auth_BK}" | sudo tee -a "${torrc}" >/dev/null
          sudo sed -i'' "/ClientOnionAuthDir .*/d" "${hs_bk_dir}"/integrate"${torrc}"
        fi
        sudo cat -s "${torrc}" "${hs_bk_dir}"/integrate"${torrc}" | sudo tee "${torrc}".tmp >/dev/null
        sudo mv "${torrc}".tmp "${torrc}"
        ## avoid duplication of services, it will keep the current machine config lines for safety
        # for service in $(sudo grep "HiddenServiceDir" "${torrc}" | cut -d " " -f2); do
        #   service_name=$(printf %s"${service##*/}")
        #   sudo sed -n "/HiddenServiceDir .*\/${service_name}$/,/^\s*$/{p}" "${torrc}" > "${torrc}".tmp
        #   sudo sed -i'' "/HiddenServiceDir .*\/${service_name}$/,/^\s*$/{d}" "${torrc}"
        #   sudo sed '/^\s*$/Q' "${torrc}".tmp > "${torrc}".mod
        #   sudo sed -i'' '1 i \ ' "${torrc}".mod; sudo sed -i'' "\$a\ " "${torrc}".mod
        #   sudo cat "${torrc}".mod | sudo tee -a "${torrc}" >/dev/null
        # done
        # sudo rm -f "${torrc}".tmp "${torrc}".mod
        #sudo cat -s "${torrc}" | sudo tee "${torrc}".tmp >/dev/null && sudo mv "${torrc}".tmp "${torrc}"
        sudo rm -rf "${hs_bk_dir}"/integrate
        ## RESTORE BACKUP FROM REMOTE
        printf "\n# Restore your configuration importing from a remote machine.\n\n"
        ## upload from remote to this instane
        printf "# Import backup file uploading to remote. On the remote terminal, run:\n"
        printf %s"\tsudo scp -r ${HS_BK_TAR} ${USER}@${local_ip}:${hs_bk_dir}/\n\n" #### remove HS_BK_TAR
        ## download from this instance
        printf "# Import backup file downloading from remote. On this terminal instance, run:\n"
        printf %s"\tsudo scp -r ${scp_target_full} ${hs_bk_dir}/${HS_BK_TAR}\n" #### remove HS_BK_TAR
        #restarting_tor
      ;;

      ## full backup needede to restore all of your hidden services and client keys
      ## folders/files included: <torrc>, <DataDir>/services/, <DataDir>/onion_auth/
      ## scp instructions to export backup to remote host
      create|CREATE)
        HS_BK_TAR="tor-hs-$(date +%Y-%m-%d-%H'h'-%M'm').tar.gz"
        printf "# Backing up the services dir, onion_auth dir and the torrc\n\n"
        mkdir -p "${hs_bk_dir}"
        ## these lines are necessary to copy the full path when creating the compressed archive
        sudo cp "${torrc}" "${torrc}".rest
        printf '\n%s\n\n' "$(sudo grep "ClientOnionAuthDir" "${torrc}")" | sudo tee "${torrc}".tmp >/dev/null
        printf '\n%s\n\n' "$(sudo sed -n "/HiddenServiceDir/,/^\s*$/{p}" "${torrc}")" | sudo tee -a "${torrc}".tmp >/dev/null
        sudo mv "${torrc}".tmp "${torrc}"
        sudo tar -cpzvf "${hs_bk_dir}"/"${HS_BK_TAR}" "${data_dir_services}" "${data_dir_auth}" "${torrc}" 2>/dev/null
        sudo mv "${torrc}".rest "${torrc}"
        sudo chown -R "${USER}:${USER}" "${hs_bk_dir}"
        set_owner_permission
        printf %s"\nsha256sum=$(sha256sum "${hs_bk_dir}"/"${HS_BK_TAR}")\n\n"
        ## upload to remote
        printf "# Export backup file uploading to remote. On this terminal instance, run:\n"
        printf %s"\tsudo scp -r ${hs_bk_dir}/${HS_BK_TAR} ${scp_target_full}\n\n"
        ## download from this instance on remote
        printf "# Export backup file downloading from remote. On the remote terminal, run:\n"
        printf %s"\tsudo scp -r ${USER}@${local_ip}:${hs_bk_dir}/${HS_BK_TAR} .\n"
      ;;

      *)
        error_msg "Invalid argument: ${action}"
    esac
  ;;


  ## This addon protects against guard discovery and related traffic analysis attacks.
  ## A guard discovery attack enables an adversary to determine the guard node(s) that are in use by a Tor client and/or Tor onion service.
  ## Once the guard node is known, traffic analysis attacks that can deanonymize an onion service (or onion service user) become easier.
  ##  TODO: hardening (as in $ sytemctl cat tor@default), but got permission denied: unable to read '/run/tor/control.authcookie'
  vanguards|VANGUARDS)
    : "${action:?$(usage)}"

    vanguards_config(){
      sudo cp "${torrc}" "${torrc}".bak
      ## Keep config with the torrc and torsocks.conf
      sudo cp -v "${data_dir}"/vanguards/vanguards-example.conf "${torrc_root}"/vanguards.conf
      sudo sed -i'' "s|control_port =.*|control_port = ${control_port}|g" "${torrc_root}"/vanguards.conf
      sudo sed -i'' "s|logfile = .*|logfile = /var/log/tor/vanguards.log|g" "${torrc_root}"/vanguards.conf
      ## Control and Authentication methods are needed. Use the easiest to configure if the manual ones are not present, else do nothing.
      ## Control methods are Port (default: 9051) and Socket (default: /run/tor/control). Prefer port because socket path may differ on different systems https://github.com/mikeperry-tor/vanguards/pull/54#issuecomment-812185302.
      if ! grep -q "ControlPort ${control_port}" "${torrc}" && ! grep -q "ControlSocket" "${torrc}"; then
        sudo sed -i'' "s/ControlPort .*/ControlPort ${control_port}/" "${torrc}"
        grep -q "ControlPort ${control_port}" "${torrc}" || printf %s"\nControlPort ${control_port}\n\n" | sudo tee -a "${torrc}" >/dev/null
      fi
      ## Authentication methods are Cookie (default: 0) and HashedPassword, to read the "control_auth_cookie". Prefer cookie because else a password is needed. If any method was already configured, use it.
      if ! grep -q "CookieAuthentication 1" "${torrc}" && ! grep -q "HashedControlPassword" "${torrc}"; then
        sudo sed -i'' "s/CookieAuthentication .*/CookieAuthentication 1/" "${torrc}"
        grep -q "CookieAuthentication" "${torrc}" || printf "\nCookieAuthentication 1\n\n" | sudo tee -a "${torrc}"  >/dev/null
      fi
      ## Edit vanguards service
      cp -v "${ONIONSERVICE_PWD}"/etc/systemd/system/vanguards@default.service /tmp/vanguards@default.service
      sed -i'' "s|torrc_root|${torrc_root}|g" /tmp/vanguards@default.service
      sed -i'' "s|tor_service|${tor_service}|g" /tmp/vanguards@default.service
      sed -i'' "s|data_dir|${data_dir}|g" /tmp/vanguards@default.service
      sed -i'' "s|tor_user|${tor_user}|g" /tmp/vanguards@default.service
      sudo cp -v /tmp/vanguards@default.service /etc/systemd/system/
      printf "\n>>>>>>>>>>>>>>>>>>>\n"
      while IFS= read -r line || [ -n "$line" ]; do printf '%s\n' "$line"; done < "/tmp/vanguards@default.service"
      #cat /tmp/vanguards@default.service
      printf ">>>>>>>>>>>>>>>>>>>\n\n"
      restarting_tor
      sudo systemctl daemon-reload
      sudo systemctl enable vanguards@default.service
      sudo systemctl restart vanguards@default.service
      sudo systemctl status vanguards@default.service --no-pager
      printf %s"${green}\n# Done\n${nocolor}"
    }

    case "${action}" in
      install|INSTALL)
        printf "# Installing Vanguards...\n\n"
        sudo -u "${tor_user}" git clone https://github.com/mikeperry-tor/vanguards.git "${data_dir}/vanguards"
        sudo -u "${tor_user}" git -C "${data_dir}"/vanguards reset --hard "${vanguards_commit}"
        vanguards_config
      ;;

      upgrade|UPGRADE)
        printf "# Upgrading Vanguards...\n\n"
        sudo -u "${tor_user}" git -C "${data_dir}"/vanguards pull -p --rebase=false
        sudo -u "${tor_user}" git -C "${data_dir}"/vanguards reset --hard "${vanguards_commit}"
        sudo -u "${tor_user}" git -C "${data_dir}"/vanguards show
        vanguards_config
      ;;

      remove|REMOVE)
        printf "# Removing Vanguards...\n\n"
        sudo rm -rfv "${data_dir}"/vanguards
        printf %s"${green}\n# Done\n${nocolor}"
      ;;

      logs|LOGS)
        sudo tail -f -n 25 /var/log/tor/vanguards.log
      ;;

      *)
        error_msg "Invalid argument: ${action}"
    esac
  ;;

  *) usage

esac
