#!/usr/bin/env sh

## DESCRIPTION
## This file lets you manage your authorized clients for hidden services
## It is a TUI for the onionservice-cli with everything integrated in this menu
##
## SYNTAX
## ./onionservice-tui
##
## Lines that begin with "## " try to explain what's going on. Lines
## that begin with just "#" are disabled commands.

[ -n "${ONIONSERVICE_PWD}" ] || { printf "\033[1;31mERROR: \${ONIONSERVICE_PWD} needs to be exported first!\033[0m\nRun: ./setup.sh -h\n"; exit 1; }
. "${ONIONSERVICE_PWD}"/.onionrc

###################
#### VARIABLES ####
i=0

: "${tor_user:?}"
: "${web_server:?}"
: "${dialog_box:?}"

: "${website_dir:?}"

: "${nocolor:?}"
: "${red:?}"
: "${green:?}"
: "${yellow:?}"
: "${blue:?}"
: "${magenta:?}"

: "${data_dir:?}"
: "${data_dir_services:?}"
: "${data_dir_auth:?}"
: "${torrc:?}"
: "${control_port:?}"

###########################
######## FUNCTIONS ########

## clear is not a posix command
clear_posix(){ printf \\033[2J\\033[H\\033[m ; }
trap 'clear_posix' EXIT


case "${dialog_box}" in
  dialog)
    #yes_flag="--yes-label"
    #no_flag="--no-label"
    ok_flag="--ok-label"
    cancel_flag="--cancel-label"
    no_cancel_flag="--no-cancel"
  ;;
  whiptail)
    whiptail_height=1
    #yes_flag="--yes-button"
    #no_flag="--no-button"
    ok_flag="--ok-button"
    cancel_flag="--cancel-button"
    no_cancel_flag="--nocancel"
  ;;
esac

return_to_tui(){
  printf %s"${yellow}\nPress ENTER to return to the TUI: ${nocolor}" >&2
  # shellcheck disable=SC2034
  read -r confirmation
}

## $1 [checklist|menu]
## $2 complementary title
service_menu(){
  dialog_type="${1}"
  compl_title="${2}"
  i=0
  for service in $(sudo -u "${tor_user}" ls "${data_dir_services}"); do
    i=$((i+1))
    onion_hostname="$(sudo -u "${tor_user}" grep -s ".onion" "${data_dir_services}"/"${service}"/hostname)"
    case "${dialog_type}" in
      checklist) service_list="$(printf "%s\n%s\n%s\n%s\n" "${service_list}" "${service}" "${onion_hostname%.onion}" 0)";;
      menu) service_list="$(printf "%s\n%s\n%s\n" "${service_list}" "${service}" "${onion_hostname%.onion}")";;
    esac
  done

  if [ -n "${service_list}" ]; then
    title="Onion Services - ${compl_title}"
    menu="\nUse spacebar to select:"
    [ "${i}" -gt 11 ] && i="11"
    case "${dialog_type}" in
      checklist)
        # shellcheck disable=SC2086
        choice_service="$("${dialog_box}" --clear --separate-output --backtitle "${backtitle}" --title "${title}" --"${dialog_type}" "${menu}" \
        "$((i+8+whiptail_height))" 80 "${i}" ${service_list} 3>&1 1>&2 2>&3)"
      ;;
      menu)
        # shellcheck disable=SC2086
        choice_service="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" --"${dialog_type}" "${menu}" \
        "$((i+8+whiptail_height))" 80 "${i}" ${service_list} 3>&1 1>&2 2>&3)"
      ;;
    esac
    service_name_list=""
    [ -n "${choice_service}" ] && service_name_list="$(printf %s"${choice_service}" | sed "s/ /,/g")"
  fi
}


###########################

title="Onion Services - Main Menu"
menu="\nUse enter/spacebar to select:"
backtitle="Onion Services Manager"
if [ -z "$(sudo -u "${tor_user}" ls "${data_dir_services}")" ]; then
  choice_main="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
  "${ok_flag}" "Select" "${no_cancel_flag}" --menu "${menu}" "$((15+whiptail_height))" 80 7 \
  "QUIT" "Exit menu and clear the screen" \
  "MAN" "Manual pages for the onionservice-cli" \
  "GUIDES" "Markdown guides by Tor Project Organization and Riseup" \
  "ENABLE" "Enable a onion service" \
  "AUTH_CLIENT" "Manage your client keys of remote service" \
  "VANGUARDS" "Add to protect against traffic analysis" \
  "IMPORT" "Import backup from another machine" \
  3>&1 1>&2 2>&3)"
else
  choice_main="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
  "${ok_flag}" "Select" "${no_cancel_flag}" --menu "${menu}" "$((22+whiptail_height))" 80 14 \
  "QUIT" "Exit menu and clear the screen" \
  "MAN" "Manual pages for the onionservice-cli" \
  "GUIDES" "Markdown guides by Tor Project Organization and Riseup" \
  "ENABLE" "Enable a onion service" \
  "DISABLE" "Disable chosen onion service" \
  "RENEW" "Renew onion service address" \
  "AUTH_SERVER" "Add or Remove client authorization from your service" \
  "AUTH_CLIENT" "Manage your client keys of remote service" \
  "CREDENTIALS" "See credentials (onion address, authorized clients)" \
  "WEB_SERVER" "Serve a website folder on onion domain" \
  "VANGUARDS" "Add to protect against traffic analysis" \
  "LOCATION" "Guided steps to add onion-location to your plainnet website" \
  "IMPORT" "Import backup from another machine" \
  "EXPORT" "Export backup to another machine" \
  3>&1 1>&2 2>&3)"
fi


case "${choice_main}" in

  MAN) man onionservice-cli;;


  GUIDES)
    i=0
    for md in "${ONIONSERVICE_PWD}"/docs/*.md; do
      i=$((i+1))
      md_list="$(printf "%s\n%s\n%s\n" "${md_list}" "${md##*/}" ".")"
    done
    title="Markdown guides"
    menu="Select a guide:"
    # shellcheck disable=SC2086
    choice_md="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
    --menu "${menu}" "$((i+7+whiptail_height))" 45 10 ${md_list} 3>&1 1>&2 2>&3)"
    [ -n "${choice_md}" ] && { pandoc "${ONIONSERVICE_PWD}"/docs/"${choice_md}" | lynx -stdin ; }
  ;;


  ENABLE)

    title="Onion Service - Activation"
    menu="Choose socket type:"
    choice_socket="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
    --menu "${menu}" "$((9+whiptail_height))" 70 2 \
    "UNIX" "unix:path (more secure)" \
    "TCP" "addr:port (leak onion address to the local network)" \
    3>&1 1>&2 2>&3)"

    SERVICE_MSG="\nName your service directory in one string and no space.\n(e.g.: torbox.ch)"
    UNIX_PORT_MSG="\nYou are able to configure up to two virtual ports. Insert them separated by space. (e.g.: 80 443)"
    TCP_PORT_MSG="\nYou are able to configure up to two virtual ports and targets, being only one virtual port required to create a service.
    \nInsert them separated by space in the following order:\nVIRPORT TARGET VIRTPORT2 TARGET2\n(e.g.: 80 5000 443 5001) (e.g.: 80 192.168.5.10:5000 443 192.168.5.10:5001)"

    case "${choice_socket}" in

      UNIX)
        service_name="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
        --inputbox "${SERVICE_MSG}" 10 60 3>&1 1>&2 2>&3)"
        if [ -n "${service_name}" ]; then
          service_ports="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
          --inputbox "${UNIX_PORT_MSG}" 10 60 3>&1 1>&2 2>&3)"
          if [ -n "${service_ports}" ]; then
            clear_posix
            # shellcheck disable=SC2086
            "${ONIONSERVICE_PWD}"/onionservice-cli on "${service_name}" 3 unix ${service_ports}
            return_to_tui
          fi
        fi
      ;;

      TCP)
        service_name="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
        --inputbox "${SERVICE_MSG}" 10 60 3>&1 1>&2 2>&3)"
        if [ -n "${service_name}" ]; then
          service_ports="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
          --inputbox "${TCP_PORT_MSG}" 13 80 3>&1 1>&2 2>&3)"
          if [ -n "${service_ports}" ]; then
            # shellcheck disable=SC2086
            "${ONIONSERVICE_PWD}"/onionservice-cli on "${service_name}" 3 tcp ${service_ports}
            return_to_tui
          fi
        fi
      ;;

    esac
  ;;


  DISABLE)
    service_menu checklist "Disable"
    if [ -n "${service_name_list}" ]; then
      title="Onion Service - Deactivation"
      menu="
DISABLE: Service will be disabled, lines from the torrc deleted but the folder will be kept.

PURGE: Service will be permanently disabled, all the directory data, including hidden service keys and clients will be deleted permanently (you won't be able to use the same onion address)."
      choice_disable="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Cancel" --menu "${menu}" "$((15+whiptail_height))" 80 2 \
      "DISABLE" "Only disable (remove configuration lines)" \
      "PURGE" "Disable and Purge HiddenServiceDir (delete onion keys)" \
      3>&1 1>&2 2>&3)"
      if [ -n "${choice_disable}" ]; then
        [ "${choice_disable}" = "PURGE" ] && purge="purge"
        clear_posix
        "${ONIONSERVICE_PWD}"/onionservice-cli off "${service_name_list}" "${purge}"
        return_to_tui
      else
        text="\nOperation canceled, nothing was executed."
        "${dialog_box}" --backtitle "${backtitle}" --title "${title}" --msgbox "${text}" 10 50
      fi
    fi
  ;;

  ## TODO: add warning as in purge before confirming.
  RENEW)
    service_menu checklist "Renew"
    if [ -n "${service_name_list}" ]; then
      clear_posix
      "${ONIONSERVICE_PWD}"/onionservice-cli renew "${service_name_list}"
      return_to_tui
    fi
  ;;


  AUTH_SERVER)
    i=0
    service_list=""
    for service in $(sudo -u "${tor_user}" ls "${data_dir_services}"); do
      ## only include services that have at least one client
      client_exist="$(sudo -u "${tor_user}" ls "${data_dir_services}"/"${service}"/authorized_clients/ | sed "s/\.auth//g")"
      if [ -n "${client_exist}" ]; then
        i=$((i+1))
        onion_hostname="$(sudo -u "${tor_user}" grep -s ".onion" "${data_dir_services}"/"${service}"/hostname)"
        service_list_menu="$(printf "%s\n%s\n%s\n" "${service_list}" "${service}" "${onion_hostname%.onion}")"
        service_list_checklist="$(printf "%s\n%s\n%s\n%s\n" "${service_list}" "${service}" "${onion_hostname%.onion}" 0)"
      fi
    done
    if [ -z "${i}" ]; then
      title="Client Authorization - Server"
      menu="\nManage client authorization of your services:"
      auth_type="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Cancel" --menu "${menu}" "$((10+whiptail_height))" 60 2 \
      "GEN" "Generate a new key pair (public and private key)" \
      "PUB" "Register the client public key" \
      3>&1 1>&2 2>&3)"
    else
      title="Client Authorization - Server"
      menu="\nManage client authorization of your services:"
      auth_type="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Cancel" --menu "${menu}" "$((13+whiptail_height))" 60 5 \
      "LIST" "List all clients for specific HiddenService" \
      "EDIT" "Edit an existing authorization" \
      "GEN" "Generate a new key pair (public and private key)" \
      "PUB" "Register the client public key" \
      "DEL" "Remove a client" \
      3>&1 1>&2 2>&3)"
    fi

    case "${auth_type}" in

      LIST)
        title="Client Authorization - Server - List "
        menu="\nUse spacebar to select:"
        [ "${i}" -gt 11 ] && i="11"
        # shellcheck disable=SC2086
        choice_service="$("${dialog_box}" --clear --separate-output --backtitle "${backtitle}" --title "${title}" --checklist "${menu}" \
        "$((i+8+whiptail_height))" 80 "${i}" ${service_list_checklist} 3>&1 1>&2 2>&3)"
        service_name_list=""
        [ -n "${choice_service}" ] && service_name_list="$(printf %s"${choice_service}" | sed "s/ /,/g")"
        if [ -n "${service_name_list}" ]; then
          clear_posix
          "${ONIONSERVICE_PWD}"/onionservice-cli auth server list "${service_name_list}"
          return_to_tui
        fi
      ;;

      EDIT)
        title="Client Authorization - Server - Edit"
        menu="\nUse spacebar to select:"
        [ "${i}" -gt 11 ] && i="11"
        # shellcheck disable=SC2086
        choice_service="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" --menu "${menu}" \
        "$((i+8+whiptail_height))" 80 "${i}" ${service_list_menu} 3>&1 1>&2 2>&3)"
        if [ -n "${choice_service}" ]; then
          service="${choice_service}"
          i=0
          for client in $(sudo -u "${tor_user}" ls "${data_dir_services}"/"${service}"/authorized_clients/ | sed "s/\.auth//g"); do
            i=$((i+1))
            client_list="$(printf "%s\n%s\n%s\n" "${client_list}" "${client}" ".")"
          done
          # shellcheck disable=SC2086
          choice_client="$("${dialog_box}" --backtitle "${backtitle}" --title "${title}" --menu "${menu}" \
          "$((i+8+whiptail_height))" 50 "${i}" ${client_list} 3>&1 1>&2 2>&3)"
          [ -n "${choice_client}" ] && sudo "${EDITOR:-vi}" "${data_dir_services}"/"${service}"/authorized_clients/"${choice_client}".auth
        fi
      ;;

      GEN)
        service_menu checklist "Auth Server Gen"
        if [ -n "${service_name_list}" ]; then
          title="Client Authorization - Server - Generate"
          menu="\nClient(s) name(s) delimited by space or/and comma (e.g.: alice, bob, carol)"
          client_name_list="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
          --inputbox "${menu}" 10 50 3>&1 1>&2 2>&3)"
          client_name_list="$(printf %s"${client_name_list}" | tr -s ' ' ',' | tr -s ',' ',')"
          if { [ -n "${service_name_list}" ] && [ -n "${client_name_list}" ]; }; then
            clear_posix
            "${ONIONSERVICE_PWD}"/onionservice-cli auth server on "${service_name_list}" "${client_name_list}"
            return_to_tui
          fi
        fi
      ;;

      PUB)
        service_menu menu "Auth Server Pub"
        if [ -n "${service_name_list}" ]; then
          title="Client Authorization - Server - Pub"
          menu="\nClient name (e.g.: alice)"
          client_name_list="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
          --inputbox "${menu}" 9 50 3>&1 1>&2 2>&3)"
          if [ -n "${client_name_list}" ]; then
            title="Client Authorization - Server - Pub"
            menu="\nClient public key in base32:"
            client_pub_key="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
            --inputbox "${menu}" 9 50 3>&1 1>&2 2>&3)"
            if [ -n "${client_pub_key}" ]; then
              clear_posix
              "${ONIONSERVICE_PWD}"/onionservice-cli auth server on "${service_name_list}" "${client_name_list}" "${client_pub_key}"
              return_to_tui
            fi
          fi
        fi
      ;;

      DEL)
        title="Client Authorization - Server - Deletion"
        menu="\nUse spacebar to select:"
        [ "${i}" -gt 11 ] && i="11"
        # shellcheck disable=SC2086
        choice_service="$("${dialog_box}" --separate-output --backtitle "${backtitle}" --title "${title}" --checklist "${menu}" \
        "$((i+8+whiptail_height))" 80 "${i}" ${service_list_checklist} 3>&1 1>&2 2>&3)"
        if [ -n "${choice_service}" ]; then
          # shellcheck disable=SC2086
          service_total=$(IFS=' '; set -f -- ${choice_service}; printf %s"${#}")
          for service in $(printf %s"${choice_service}"); do
            client="$(sudo -u "${tor_user}" ls "${data_dir_services}"/"${service}"/authorized_clients/ | sed "s/\.auth//g")"
            client_list="$(printf "%s\n%s\n" "${client_list}" "${client}")"
          done
          i=0
          ## intersection of clients on the chosen services
          for client in $(printf %s"${client_list}" | tr " " "\n" | sort | uniq -c | grep "${service_total}" | sed "s/${service_total}//g" | tr -s "\n" " "); do
            i=$((i+1))
            client_build_list="$(printf "%s\n%s\n%s\n%s\n" "${client_build_list}" "${client}" "." 0)"
          done
          if [ -z "${client_build_list}" ]; then
            title="Onion Service - INFO"
            text_no_client="\nNo client exist inside the intersection of the chosen services."
            "${dialog_box}" --backtitle "${backtitle}" --title "${title}" --msgbox "${text_no_client}" 10 50
          else
            [ "${i}" -gt 11 ] && i="11"
            # shellcheck disable=SC2086
            choice_client="$("${dialog_box}" --separate-output --backtitle "${backtitle}" --title "${title}" --checklist "${menu}" \
            "$((i+8+whiptail_height))" 50 "${i}" ${client_build_list} 3>&1 1>&2 2>&3)"
          fi
          if [ -n "${choice_client}" ]; then
            service_name_list="$(printf %s"${choice_service}" | sed "s/ /,/g")"
            client_name_list="$(printf %s"${choice_client}" | sed 's/ /,/g')"
          fi
        fi
        if [ -n "${client_name_list}" ]; then
          clear_posix
          "${ONIONSERVICE_PWD}"/onionservice-cli auth server off "${service_name_list}" "${client_name_list}"
          return_to_tui
        fi
      ;;

    esac
  ;;


  AUTH_CLIENT)
    i=0
    for onion_auth in $(sudo -u "${tor_user}" ls "${data_dir_auth}"/); do
      onion_auth_name=${onion_auth%.auth_private}
      i=$((i+1))
      onion_auth_list="$(printf "%s\n%s\n%s\n" "${onion_auth_list}" "${onion_auth_name}" ".")"
    done
    title="Client Authorization - Client"
    menu="\nAs the onion service client:"
    if [ -z "${onion_auth_list}" ]; then
      auth_type="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Cancel" --menu "${menu}" "$((10+whiptail_height))" 80 2 \
      "GEN" "Generate a new key pair (public and private key)" \
      "PRIV" "Register your private key" \
      3>&1 1>&2 2>&3)"
    else
      auth_type="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Cancel" --menu "${menu}" "$((14+whiptail_height))" 80 5 \
      "LIST" "List all the authorizations inside ClientOnionAuthDir" \
      "EDIT" "Edit your client authorizations" \
      "GEN" "Generate a new key pair (public and private key)" \
      "PRIV" "Register your private key" \
      "DEL" "Remove expired authorization" \
      3>&1 1>&2 2>&3)"
    fi

    case "${auth_type}" in

      LIST)
        "${ONIONSERVICE_PWD}"/onionservice-cli auth client list
        return_to_tui
      ;;

      EDIT)
        menu="\nUse spacebar to select:"
        [ "${i}" -gt 11 ] && i="11"
        # shellcheck disable=SC2086
        choice_onion_auth="$("${dialog_box}" --title "${title}" --menu "${menu}" \
        "$((i+8+whiptail_height))" 80 "${i}" ${onion_auth_list} 3>&1 1>&2 2>&3)"
        [ -n "${choice_onion_auth}" ] && sudo "${EDITOR:-vi}" "${data_dir_auth}"/"${choice_onion_auth}".auth_private
      ;;

      GEN)
        menu="\nInsert the onion address of the service you want to authenticate:"
        onion_hostname="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
        --inputbox "${menu}" 9 80 3>&1 1>&2 2>&3)"
        if [ -n "${onion_hostname}" ]; then
          clear_posix
          "${ONIONSERVICE_PWD}"/onionservice-cli auth client on "${onion_hostname}"
          return_to_tui
        fi
      ;;

      PRIV)
        menu="\nInsert the onion address of the service you want to authenticate:"
        onion_hostname="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
        --inputbox "${menu}" 9 80 3>&1 1>&2 2>&3)"
        menu="Insert the client's private key:"
        client_priv_key="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
        --inputbox "${menu}" 9 80 3>&1 1>&2 2>&3)"
        if { [ -n "${onion_hostname}" ] && [ -n "${client_priv_key}" ]; }; then
          clear_posix
          "${ONIONSERVICE_PWD}"/onionservice-cli auth client on "${onion_hostname}" "${client_priv_key}"
          return_to_tui
        fi
      ;;

      DEL)
        menu="\nUse spacebar to select:"
        [ "${i}" -gt 11 ] && i="11"
        # shellcheck disable=SC2086
        choice_onion_auth="$("${dialog_box}" --separate-output --title "${title}" --checklist "${menu}" \
        "$((i+8+whiptail_height))" 80 "${i}" ${onion_auth_list} 3>&1 1>&2 2>&3)"
        [ -n "${choice_onion_auth}" ] && ONION_AUTH_NAME_LIST="$(printf %s"${ONION_AUTH_NAME_LIST}" | sed "s/ /,/g")"
        if [ -n "${ONION_AUTH_NAME_LIST}" ]; then
          clear_posix
          "${ONIONSERVICE_PWD}"/onionservice-cli auth client off "${ONION_AUTH_NAME_LIST}"
          return_to_tui
        fi
      ;;

    esac
  ;;


  CREDENTIALS)
    service_menu checklist "Credentials"
    if [ -n "${service_name_list}" ]; then
      clear_posix
      "${ONIONSERVICE_PWD}"/onionservice-cli list "${service_name_list}"
      return_to_tui
    fi
  ;;


  LOCATION)
    service_menu menu "Location"
    if [ -n "${service_name_list}" ]; then
      title="Onion-Location"
      choice_action="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Exit" --menu "${menu}" "$((11+whiptail_height))" 50 3 \
      "NGINX" "Nginx web server header" \
      "APACHE" "Apache web server header" \
      "HTML" "Html <meta> http-equiv attribute" \
      3>&1 1>&2 2>&3)"
      if [ -n "${choice_action}" ]; then
        clear_posix
        "${ONIONSERVICE_PWD}"/onionservice-cli location "${choice_action}" "${service_name_list}"
        return_to_tui
      fi
    fi
  ;;


  WEB_SERVER)
    title="Web server - Status"
    menu="\nWould you like to enable or disable serving a website?"
    status="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" --menu "${menu}" "$((12+whiptail_height))" 50 3 \
    "LIST" "List enabled websites" \
    "ON" "Serve website" \
    "OFF" "Stop serving website" \
    3>&1 1>&2 2>&3)"
    if [ "${status}" = "LIST" ]; then
      clear_posix
      "${ONIONSERVICE_PWD}"/onionservice-cli "${web_server}" "${status}"
      return_to_tui
    elif [ "${status}" = "ON" ]; then
      service_menu menu "Web server "
      if [ -n "${service_name_list}" ]; then
        i=0
        for folder in $(sudo ls "${website_dir}"); do
          i=$((i+1))
          folder_list="$(printf "%s\n%s\n%s\n" "${folder_list}" "${folder}" ".")"
        done
        title="Folder"
        menu="\nUse spacebar to select:"
        [ "${i}" -gt 11 ] && i="11"
        # shellcheck disable=SC2086
        choice_folder="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" --menu "${menu}" \
        "$((i+8+whiptail_height))" 50 "${i}" ${folder_list} 3>&1 1>&2 2>&3)"
        [ -n "${choice_folder}" ] && folder_name_list="$(printf %s"${choice_folder}" | sed "s/ /,/g")"
        if [ -n "${folder_name_list}" ]; then
          clear_posix
          "${ONIONSERVICE_PWD}"/onionservice-cli web "${status}" "${service_name_list}" "${folder_name_list}"
          return_to_tui
        fi
      fi
    elif [ "${status}" = "OFF" ]; then
      i=0
      for service in $(sudo ls /etc/"${web_server}"/sites-enabled/ | sed "s/-onion.conf//g"); do
        i=$((i+1))
        service_list="$(printf "%s\n%s\n" "${service_list}" "${service}" "." 0)"
      done
      title="Web Server - Disable Site"
      menu="\nUse spacebar to select:"
      [ "${i}" -gt 11 ] && i="11"
      # shellcheck disable=SC2086
      choice_service="$("${dialog_box}" --separate-output --clear --backtitle "${backtitle}" --title "${title}" --checklist "${menu}" \
      "$((i+8+whiptail_height))" 50 "${i}" ${service_list} 3>&1 1>&2 2>&3)"
      [ -n "${choice_service}" ] && service_name_list="$(printf %s"${choice_service}" | sed "s/ /,/g")"
      if [ -n "${service_name_list}" ]; then
        clear_posix
        "${ONIONSERVICE_PWD}"/onionservice-cli web "${status}" "${service_name_list}"
        return_to_tui
      fi
    fi
  ;;


  VANGUARDS)
    title="Vanguards"
    if [ -z "$(sudo -u "${tor_user}" ls "${data_dir}"/vanguards)" ]; then
      choice_action="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Exit" --menu "${menu}" "$((9+whiptail_height))" 50 1 \
      "INSTALL" "Use Vanguards protections" 3>&1 1>&2 2>&3)"
    else
      choice_action="$("${dialog_box}" --clear --backtitle "${backtitle}" --title "${title}" \
      "${ok_flag}" "Select" "${cancel_flag}" "Exit" --menu "${menu}" "$((11+whiptail_height))" 50 3 \
      "LOGS" "Follow vanguards logs" \
      "UPGRADE" "Set new config and upgrade" \
      "REMOVE" "Delete the Vanguards directory" \
      3>&1 1>&2 2>&3)"
    fi
    if [ "${choice_action}" = "LOGS" ]; then
      clear_posix
      trap '"${ONIONSERVICE_PWD}"/onionservice-tui; exit 0' INT
      sudo tail -f -n 25 /var/log/tor/vanguards.log
    elif [ -n "${choice_action}" ]; then
      clear_posix
      "${ONIONSERVICE_PWD}"/onionservice-cli vanguards "${choice_action}"
      return_to_tui
    fi
  ;;


  IMPORT)
    "${ONIONSERVICE_PWD}"/onionservice-cli backup integrate
    return_to_tui
  ;;


  EXPORT)
    "${ONIONSERVICE_PWD}"/onionservice-cli backup create
    return_to_tui
  ;;


  QUIT) exit 0;;

esac

clear_posix
"${ONIONSERVICE_PWD}"/onionservice-tui
